/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as servicesRouteImport } from './routes/services'
import { Route as sacramentMinistersRouteImport } from './routes/sacrament-ministers'
import { Route as fellowshipMinistersRouteImport } from './routes/fellowship-ministers'
import { Route as eventsRouteImport } from './routes/events'
import { Route as contactRouteImport } from './routes/contact'
import { Route as ceremonyMinistersRouteImport } from './routes/ceremony-ministers'
import { Route as faqDetailRouteImport } from './routes/faq-detail'
import { Route as indexRouteImport } from './routes/index'
import { Route as membersDotresourcesRouteImport } from './routes/members.resources'
import { Route as membersDoterrorRouteImport } from './routes/members.error'
import { Route as membersDotdashboardRouteImport } from './routes/members.dashboard'

const servicesRoute = servicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const sacramentMinistersRoute = sacramentMinistersRouteImport.update({
  id: '/sacrament-ministers',
  path: '/sacrament-ministers',
  getParentRoute: () => rootRouteImport,
} as any)
const fellowshipMinistersRoute = fellowshipMinistersRouteImport.update({
  id: '/fellowship-ministers',
  path: '/fellowship-ministers',
  getParentRoute: () => rootRouteImport,
} as any)
const eventsRoute = eventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const contactRoute = contactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ceremonyMinistersRoute = ceremonyMinistersRouteImport.update({
  id: '/ceremony-ministers',
  path: '/ceremony-ministers',
  getParentRoute: () => rootRouteImport,
} as any)
const faqDetailRoute = faqDetailRouteImport.update({
  id: '/$faqSlug',
  path: '/$faqSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const membersDotresourcesRoute = membersDotresourcesRouteImport.update({
  id: '/members/resources',
  path: '/members/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const membersDoterrorRoute = membersDoterrorRouteImport.update({
  id: '/members/error',
  path: '/members/error',
  getParentRoute: () => rootRouteImport,
} as any)
const membersDotdashboardRoute = membersDotdashboardRouteImport.update({
  id: '/members/dashboard',
  path: '/members/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/$faqSlug': typeof faqDetailRoute
  '/ceremony-ministers': typeof ceremonyMinistersRoute
  '/contact': typeof contactRoute
  '/events': typeof eventsRoute
  '/fellowship-ministers': typeof fellowshipMinistersRoute
  '/sacrament-ministers': typeof sacramentMinistersRoute
  '/services': typeof servicesRoute
  '/members/dashboard': typeof membersDotdashboardRoute
  '/members/error': typeof membersDoterrorRoute
  '/members/resources': typeof membersDotresourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/$faqSlug': typeof faqDetailRoute
  '/ceremony-ministers': typeof ceremonyMinistersRoute
  '/contact': typeof contactRoute
  '/events': typeof eventsRoute
  '/fellowship-ministers': typeof fellowshipMinistersRoute
  '/sacrament-ministers': typeof sacramentMinistersRoute
  '/services': typeof servicesRoute
  '/members/dashboard': typeof membersDotdashboardRoute
  '/members/error': typeof membersDoterrorRoute
  '/members/resources': typeof membersDotresourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/$faqSlug': typeof faqDetailRoute
  '/ceremony-ministers': typeof ceremonyMinistersRoute
  '/contact': typeof contactRoute
  '/events': typeof eventsRoute
  '/fellowship-ministers': typeof fellowshipMinistersRoute
  '/sacrament-ministers': typeof sacramentMinistersRoute
  '/services': typeof servicesRoute
  '/members/dashboard': typeof membersDotdashboardRoute
  '/members/error': typeof membersDoterrorRoute
  '/members/resources': typeof membersDotresourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$faqSlug'
    | '/ceremony-ministers'
    | '/contact'
    | '/events'
    | '/fellowship-ministers'
    | '/sacrament-ministers'
    | '/services'
    | '/members/dashboard'
    | '/members/error'
    | '/members/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$faqSlug'
    | '/ceremony-ministers'
    | '/contact'
    | '/events'
    | '/fellowship-ministers'
    | '/sacrament-ministers'
    | '/services'
    | '/members/dashboard'
    | '/members/error'
    | '/members/resources'
  id:
    | '__root__'
    | '/'
    | '/$faqSlug'
    | '/ceremony-ministers'
    | '/contact'
    | '/events'
    | '/fellowship-ministers'
    | '/sacrament-ministers'
    | '/services'
    | '/members/dashboard'
    | '/members/error'
    | '/members/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  faqDetailRoute: typeof faqDetailRoute
  ceremonyMinistersRoute: typeof ceremonyMinistersRoute
  contactRoute: typeof contactRoute
  eventsRoute: typeof eventsRoute
  fellowshipMinistersRoute: typeof fellowshipMinistersRoute
  sacramentMinistersRoute: typeof sacramentMinistersRoute
  servicesRoute: typeof servicesRoute
  membersDotdashboardRoute: typeof membersDotdashboardRoute
  membersDoterrorRoute: typeof membersDoterrorRoute
  membersDotresourcesRoute: typeof membersDotresourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof servicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sacrament-ministers': {
      id: '/sacrament-ministers'
      path: '/sacrament-ministers'
      fullPath: '/sacrament-ministers'
      preLoaderRoute: typeof sacramentMinistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowship-ministers': {
      id: '/fellowship-ministers'
      path: '/fellowship-ministers'
      fullPath: '/fellowship-ministers'
      preLoaderRoute: typeof fellowshipMinistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof eventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof contactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceremony-ministers': {
      id: '/ceremony-ministers'
      path: '/ceremony-ministers'
      fullPath: '/ceremony-ministers'
      preLoaderRoute: typeof ceremonyMinistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$faqSlug': {
      id: '/$faqSlug'
      path: '/$faqSlug'
      fullPath: '/$faqSlug'
      preLoaderRoute: typeof faqDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/resources': {
      id: '/members/resources'
      path: '/members/resources'
      fullPath: '/members/resources'
      preLoaderRoute: typeof membersDotresourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/error': {
      id: '/members/error'
      path: '/members/error'
      fullPath: '/members/error'
      preLoaderRoute: typeof membersDoterrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/dashboard': {
      id: '/members/dashboard'
      path: '/members/dashboard'
      fullPath: '/members/dashboard'
      preLoaderRoute: typeof membersDotdashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  faqDetailRoute: faqDetailRoute,
  ceremonyMinistersRoute: ceremonyMinistersRoute,
  contactRoute: contactRoute,
  eventsRoute: eventsRoute,
  fellowshipMinistersRoute: fellowshipMinistersRoute,
  sacramentMinistersRoute: sacramentMinistersRoute,
  servicesRoute: servicesRoute,
  membersDotdashboardRoute: membersDotdashboardRoute,
  membersDoterrorRoute: membersDoterrorRoute,
  membersDotresourcesRoute: membersDotresourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
