/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as indexRouteImport } from './routes/index'
import { Route as membersDotresourcesRouteImport } from './routes/members.resources'
import { Route as membersDoterrorRouteImport } from './routes/members.error'
import { Route as membersDotdashboardRouteImport } from './routes/members.dashboard'

const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const membersDotresourcesRoute = membersDotresourcesRouteImport.update({
  id: '/members/resources',
  path: '/members/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const membersDoterrorRoute = membersDoterrorRouteImport.update({
  id: '/members/error',
  path: '/members/error',
  getParentRoute: () => rootRouteImport,
} as any)
const membersDotdashboardRoute = membersDotdashboardRouteImport.update({
  id: '/members/dashboard',
  path: '/members/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/members/dashboard': typeof membersDotdashboardRoute
  '/members/error': typeof membersDoterrorRoute
  '/members/resources': typeof membersDotresourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/members/dashboard': typeof membersDotdashboardRoute
  '/members/error': typeof membersDoterrorRoute
  '/members/resources': typeof membersDotresourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/members/dashboard': typeof membersDotdashboardRoute
  '/members/error': typeof membersDoterrorRoute
  '/members/resources': typeof membersDotresourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/members/dashboard'
    | '/members/error'
    | '/members/resources'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/members/dashboard' | '/members/error' | '/members/resources'
  id:
    | '__root__'
    | '/'
    | '/members/dashboard'
    | '/members/error'
    | '/members/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  membersDotdashboardRoute: typeof membersDotdashboardRoute
  membersDoterrorRoute: typeof membersDoterrorRoute
  membersDotresourcesRoute: typeof membersDotresourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/resources': {
      id: '/members/resources'
      path: '/members/resources'
      fullPath: '/members/resources'
      preLoaderRoute: typeof membersDotresourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/error': {
      id: '/members/error'
      path: '/members/error'
      fullPath: '/members/error'
      preLoaderRoute: typeof membersDoterrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/dashboard': {
      id: '/members/dashboard'
      path: '/members/dashboard'
      fullPath: '/members/dashboard'
      preLoaderRoute: typeof membersDotdashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  membersDotdashboardRoute: membersDotdashboardRoute,
  membersDoterrorRoute: membersDoterrorRoute,
  membersDotresourcesRoute: membersDotresourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
